GET http://localhost:5142/category

###

GET http://localhost:5142/category/2

###

POST http://localhost:5142/category
Content-Type: application/json

{
    "CategoryName": "Miscallaneous"
}

###

DELETE http://localhost:5142/category/1