GET http://localhost:5142/creds

###

GET http://localhost:5142/creds/3

###

POST http://localhost:5142/creds
Content-Type: application/json

{
    "ServiceName": "Angry Cat Services",
    "Password": "1234567"
}

### 

DELETE http://localhost:5142/creds/3

### 

PATCH http://localhost:5142/creds/3
Content-Type: application/json
{
    "ServiceName": "12346"
}
